### ISSUE TITLE
Node.js deprecation

### ISSUE THREAD

**Issue by DThorpFF** [vakus/dotnet-deployment-versioning#117]
Warnings have started to appear on builds for the Node.js package being deprecated.

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: vakus/dotnet-deployment-versioning@v1.3.1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

**Comment by vakus** [comment]
Hi,

Thanks for reporting this, I have now upgraded the package to use Node20, and released new version v1.4.0.

Please update your github workflow to use the new version to stop seeing the warning, you will need something like this

```yaml
      - uses: vakus/dotnet-deployment-versioning@v1.4.0
```

This change should be completely compatible with v1.3.1 so you should not need to change any extra settings if you use them.

If you need more details please check the [usage section](https://github.com/vakus/dotnet-deployment-versioning/tree/v1.4.0?tab=readme-ov-file#usage), and if you are still unsure or have any other issue, feel free to open a new issue.

Thanks
